name: Go

on:
  push:
    branches: [ "main", "dev0" ]
  pull_request:
    branches: [ "main", "dev0" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build_and_test
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'

      - name: Build
        run: go build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build_and_test
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'

      - name: Test
        run: go test
